/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/modeles/Bague.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bague(props) {
  const { nodes, materials } = useGLTF('./modeles/Bague.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.597, 4.27, -2.635]} rotation={[0, 1.536, 0]} scale={[0.294, 0.27, 0.294]}>
        <mesh geometry={nodes.Cylinder020_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder020_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder020_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder020_4.geometry} material={materials['Material.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('./modeles/Bague.glb')
