/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/modeles/Ring.gltf 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export function Ring(props) {
  const { nodes, materials } = useGLTF('./modeles/Ring.gltf')
  const ref = useRef();
  const tl = useRef();


  useLayoutEffect(()=> {
    tl.current = gsap.timeline();

    tl.current.to(
      ref.current.rotation,
      {
        duration:2, x: 3,y: 2
      },
      0
    );

    },[]);

  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0,0,0]} rotation={[90, 0, 0]} scale={[1, 1, 1]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.ring} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Ring} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('./modeles/Ring.gltf')
